service: celsus-image-processing

custom:
  config: ${file(./infra.json)}

provider:
  name: aws
  runtime: nodejs12.x
  versionFunctions: false
  memorySize: 1024
  region: ${self:custom.config.region}
  stage: ${self:custom.config.environment}
  profile: serverless-admin-profile
  timeout: 30
  tags:
    application: 'celsus'
    owner: 'serverless'
  stackTags:
    application: 'celsus'
    owner: 'serverless'
  deploymentBucket:
    blockPublicAccess: true
    tags:
      application: 'celsus'
      owner: 'serverless'

package:
  exclude:
    - .env
    - .vscode/**
    - .travis.yml
    - coverage/**
    - test/**
    - cheatsheet.txt

functions:
  resize:
    name: resize-image
    image: ${self:custom.config.imageResizeRepositoryUrl}@sha256:1aa06e5be68afbb3c50e76444b3dc13a278313ba86e70aa5ba07bdf8923f0a26
