service: celsus-image-processing

plugins:
  - serverless-api-compression # Enable AWS API Gateway gzip compression

custom:
  contentCompression: 1024 # API Gateway gzip compression threshold (in bytes)

provider:
  name: aws
  runtime: nodejs6.10
  versionFunctions: false
  memorySize: 1024
  region: eu-west-2
  stage: dev
  endpointType: REGIONAL
  profile: serverless-admin-profile

package:
  exclude:
    - .env
    - .vscode/**
    - .travis.yml
    - coverage/**
    - test/**
    - cheatsheet.txt

functions:
  resize:
    handler: handler.resize
    name: resize
    events:
      - http:
          path: v1/resize
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-2:671123374425:userpool/eu-west-2_ocAf57dZ3
