service: celsus-image-processing

plugins:
  - serverless-domain-manager

custom:
  config: ${file(./infra.json)}
  customDomain:
    domainName: "api-celsus.isnan.eu"
    certificateArn: ${self:custom.config.certificate}
    hostedZoneId: ${self:custom.config.hostedZone}
    basePath: "image-processing"
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: edge

provider:
  name: aws
  runtime: nodejs8.10
  versionFunctions: false
  memorySize: 1024
  region: ${self:custom.config.region}
  stage: ${self:custom.config.environment}
  endpointType: EDGE
  profile: serverless-admin-profile
  # >>> Enable Gzip compression on AWS APi Gateway
  apiGateway:
    minimumCompressionSize: 1024 # in bytes
  # <<< Enable Gzip compression on AWS APi Gateway

package:
  exclude:
    - .env
    - .vscode/**
    - .travis.yml
    - coverage/**
    - test/**
    - cheatsheet.txt

functions:
  resize:
    handler: handler.resize
    name: resize
    events:
      - http:
          path: v1/resize
          method: post
          cors: true
          authorizer:
            arn: ${self:custom.config.userPoolArn}
