service: celsus-image-processing

custom:
  config: ${file(./infra.json)}

provider:
  name: aws
  runtime: nodejs12.x
  versionFunctions: false
  memorySize: 1024
  region: ${self:custom.config.region}
  stage: ${self:custom.config.environment}
  profile: serverless-admin-profile
  timeout: 30

package:
  exclude:
    - .env
    - .vscode/**
    - .travis.yml
    - coverage/**
    - test/**
    - cheatsheet.txt

functions:
  resize:
    handler: handler.resize
    name: resize-image
