service: celsus-image-processing

provider:
  name: aws
  runtime: nodejs8.10
  versionFunctions: false
  memorySize: 1024
  region: eu-west-2
  stage: dev
  endpointType: REGIONAL
  profile: serverless-admin-profile
  # >>> Enable Gzip compression on AWS APi Gateway
  apiGateway:
    minimumCompressionSize: 1024 # in bytes
  # <<< Enable Gzip compression on AWS APi Gateway

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: "api-celsus.isnan.eu"
    certificateName: "*.isnan.eu"
    hostedZoneId: ZWC66FN0XU6P9
    basePath: "image-processing"
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: regional

package:
  exclude:
    - .env
    - .vscode/**
    - .travis.yml
    - coverage/**
    - test/**
    - cheatsheet.txt

functions:
  resize:
    handler: handler.resize
    name: resize
    events:
      - http:
          path: v1/resize
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-2:671123374425:userpool/eu-west-2_ocAf57dZ3
